image: gitpod/workspace-python:3.11

tasks:
  - init: |
      pip install -r requirements.txt && \
      playwright install && \
      chmod +x gitpod-setup.sh && \
      ./gitpod-setup.sh

  - command: echo "✅ Gitpod environment ready!"

vscode:
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance